api_platform:
    type: api_platform
    prefix: /api
    resource:
        swagger:
            api_keys:
                apiKey:
                    name: Authorization
                    type: header
        mapping:
            paths: [ '%kernel.project_dir%/src/Entity' ]
        patch_formats:
            json: [ 'application/merge-patch+json' ]
